//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.WindowsForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int id { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> id_user_access { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string position { get; set; }
        public Nullable<int> id_subsidiary_companies_region { get; set; }
        public Nullable<int> id_education { get; set; }
        public string expiriens { get; set; }
        public Nullable<System.DateTime> date_begin { get; set; }
        public System.DateTime date_up { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
    
        public virtual Employees_education Employees_education { get; set; }
        public virtual User_access User_access { get; set; }
    }
}
