//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.WindowsForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.Sale_basket = new HashSet<Sale_basket>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_employess { get; set; }
        public Nullable<decimal> discont { get; set; }
        public Nullable<decimal> payment { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> id_subsidiary_companies_region { get; set; }
        public System.DateTime date_up { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale_basket> Sale_basket { get; set; }
        public virtual Subsidiary_companies_region Subsidiary_companies_region { get; set; }
    }
}
