//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.WindowsForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_basket
    {
        public int id { get; set; }
        public Nullable<int> id_goods { get; set; }
        public Nullable<int> id_sale { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
