//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.WindowsForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccess_history
    {
        public int id { get; set; }
        public Nullable<int> id_доступа_пользователя { get; set; }
        public System.DateTime дата_входа { get; set; }
        public Nullable<System.DateTime> дата_выхода { get; set; }
    }
}
